// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannel) DeepCopyInto(out *AlertChannel) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannel.
func (in *AlertChannel) DeepCopy() *AlertChannel {
	if in == nil {
		return nil
	}
	out := new(AlertChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelBasicAuth) DeepCopyInto(out *AlertChannelBasicAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelBasicAuth.
func (in *AlertChannelBasicAuth) DeepCopy() *AlertChannelBasicAuth {
	if in == nil {
		return nil
	}
	out := new(AlertChannelBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelHttpConfig) DeepCopyInto(out *AlertChannelHttpConfig) {
	*out = *in
	out.BasicAuth = in.BasicAuth
	out.TlsConfig = in.TlsConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelHttpConfig.
func (in *AlertChannelHttpConfig) DeepCopy() *AlertChannelHttpConfig {
	if in == nil {
		return nil
	}
	out := new(AlertChannelHttpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelImage) DeepCopyInto(out *AlertChannelImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelImage.
func (in *AlertChannelImage) DeepCopy() *AlertChannelImage {
	if in == nil {
		return nil
	}
	out := new(AlertChannelImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelLink) DeepCopyInto(out *AlertChannelLink) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelLink.
func (in *AlertChannelLink) DeepCopy() *AlertChannelLink {
	if in == nil {
		return nil
	}
	out := new(AlertChannelLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelSettings) DeepCopyInto(out *AlertChannelSettings) {
	*out = *in
	out.TlsConfig = in.TlsConfig
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.HttpConfig = in.HttpConfig
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]AlertChannelImage, len(*in))
		copy(*out, *in)
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]AlertChannelLink, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelSettings.
func (in *AlertChannelSettings) DeepCopy() *AlertChannelSettings {
	if in == nil {
		return nil
	}
	out := new(AlertChannelSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelTLSConfig) DeepCopyInto(out *AlertChannelTLSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelTLSConfig.
func (in *AlertChannelTLSConfig) DeepCopy() *AlertChannelTLSConfig {
	if in == nil {
		return nil
	}
	out := new(AlertChannelTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMonitoring) DeepCopyInto(out *ApplicationMonitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMonitoring.
func (in *ApplicationMonitoring) DeepCopy() *ApplicationMonitoring {
	if in == nil {
		return nil
	}
	out := new(ApplicationMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationMonitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMonitoringList) DeepCopyInto(out *ApplicationMonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationMonitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMonitoringList.
func (in *ApplicationMonitoringList) DeepCopy() *ApplicationMonitoringList {
	if in == nil {
		return nil
	}
	out := new(ApplicationMonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationMonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMonitoringSpec) DeepCopyInto(out *ApplicationMonitoringSpec) {
	*out = *in
	if in.AlertChannels != nil {
		in, out := &in.AlertChannels, &out.AlertChannels
		*out = make([]AlertChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMonitoringSpec.
func (in *ApplicationMonitoringSpec) DeepCopy() *ApplicationMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMonitoringStatus) DeepCopyInto(out *ApplicationMonitoringStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMonitoringStatus.
func (in *ApplicationMonitoringStatus) DeepCopy() *ApplicationMonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationMonitoringStatus)
	in.DeepCopyInto(out)
	return out
}
